// Catalogue des flyers metiers : un metier = un flyer partageable
// (/metiers/[slug]) + un badge dans la section "Metiers" de la home.
// Les demandes sont ecrites comme on les dirait a son agent, telles quelles :
// c'est ce qui rend le flyer concret, ne pas les reformuler en features.

export const METIERS = [
  {
    slug: "restaurateur",
    emoji: "\u{1F37D}\u{FE0F}",
    badge: "Restaurateur",
    title: "Restaurateur / Food truck",
    demandes: [
      "Réponds à mes 15 derniers avis Google. Fais-moi signe si un avis est en dessous de 3 étoiles.",
      "Tiens la liste de mes stocks et de mes fournisseurs, et contacte-les quand une réserve est basse.",
      "Gère le planning de mes employés en tenant compte des contraintes de chacun : horaires, contrats.",
      "Fais-moi un point sur mes mails. S'il n'y a rien d'important, dis-le-moi aussi.",
      "Envoie cette facture sur Qonto ou Revolut Business.",
      "Réponds au téléphone en dehors des horaires d'ouverture et prends les réservations.",
    ],
  },
  {
    slug: "musicien",
    emoji: "\u{1F3B5}",
    badge: "Musicien",
    title: "Musicien / Prof de musique",
    demandes: [
      "Relance les élèves qui n'ont pas payé leur mois de cours.",
      "Gère mon planning de cours et évite les chevauchements entre élèves.",
      "Réponds aux demandes de nouveaux élèves sur Instagram et WhatsApp, propose des créneaux d'essai.",
      "Prépare une facture pour chaque cachet de concert et envoie-la sur Qonto.",
      "Fais un point sur mes mails et dis-moi s'il y a une proposition de concert.",
      "Relance les salles qui n'ont pas répondu à mes demandes de booking depuis 2 semaines.",
    ],
  },
  {
    slug: "agent-immobilier",
    emoji: "\u{1F3E0}",
    badge: "Agent immobilier",
    title: "Agent immobilier",
    demandes: [
      "Réponds aux demandes de visite reçues sur SeLoger et Leboncoin, propose des créneaux.",
      "Relance les acquéreurs restés silencieux depuis leur visite.",
      "Rédige une annonce optimisée à partir des photos et des infos du bien.",
      "Fais un point sur mes mails chaque matin et priorise les mandats en cours.",
      "Prépare le compte-rendu de visite et envoie-le au propriétaire.",
      "Surveille les annonces concurrentes sur mon secteur et préviens-moi des baisses de prix.",
    ],
  },
  {
    slug: "notaire",
    emoji: "\u{2696}\u{FE0F}",
    badge: "Notaire",
    title: "Notaire",
    demandes: [
      "Fais un point sur mes mails chaque matin et signale-moi les échéances urgentes.",
      "Relance les clients qui n'ont pas renvoyé les pièces demandées pour leur dossier.",
      "Prépare un premier récapitulatif de dossier à partir des pièces reçues.",
      "Gère la prise de rendez-vous et évite les conflits d'agenda avec mes associés.",
      "Classe les mails par dossier en cours et résume-les-moi.",
      "Prépare les factures d'honoraires et envoie-les sur mon outil de facturation.",
    ],
  },
  {
    slug: "epicerie",
    emoji: "\u{1F6D2}",
    badge: "Épicerie",
    title: "Commerce de proximité / Épicerie",
    demandes: [
      "Tiens la liste de mes stocks et de mes fournisseurs, et contacte-les quand une réserve est basse.",
      "Réponds à mes avis Google et fais-moi signe si un avis est en dessous de 3 étoiles.",
      "Gère le planning de mes employés selon leurs contrats et leurs disponibilités.",
      "Fais un point sur mes mails fournisseurs, même s'il n'y a rien d'important.",
      "Envoie mes factures fournisseurs sur Qonto pour le suivi comptable.",
      "Réponds aux clients sur Instagram : horaires, disponibilité des produits.",
    ],
  },
  {
    slug: "electricien",
    emoji: "\u{26A1}",
    badge: "Électricien",
    title: "Électricien",
    demandes: [
      "Réponds aux demandes de devis reçues par mail ou téléphone pendant que je suis sur un chantier.",
      "Prépare mes devis à partir d'une description orale du chantier.",
      "Relance les clients dont le devis est en attente depuis plus d'une semaine.",
      "Organise mon planning d'interventions en tenant compte des trajets entre chantiers.",
      "Prépare mes factures et envoie-les sur mon outil de compta.",
      "Fais un point sur mes mails et dis-moi s'il y a quelque chose d'important.",
    ],
  },
  {
    slug: "plombier",
    emoji: "\u{1F527}",
    badge: "Plombier",
    title: "Plombier",
    demandes: [
      "Réponds au téléphone en dehors des horaires et fais le tri entre les vraies urgences et le reste.",
      "Prépare un devis à partir des photos et de la description envoyées par le client.",
      "Organise mon planning selon les urgences et la localisation des chantiers.",
      "Relance les clients qui ont une facture impayée.",
      "Commande les pièces manquantes chez mes fournisseurs habituels.",
      "Fais un point sur mes mails chaque matin.",
    ],
  },
  {
    slug: "coiffeur",
    emoji: "\u{1F487}",
    badge: "Coiffeur",
    title: "Coiffeur / Institut de beauté",
    demandes: [
      "Prends les rendez-vous par téléphone et SMS, même en dehors des horaires d'ouverture.",
      "Relance les clients qui n'ont pas pris rendez-vous depuis plus de 2 mois.",
      "Réponds à mes avis Google et signale-moi ceux en dessous de 3 étoiles.",
      "Gère le planning de mon équipe selon les contrats de chacun.",
      "Prépare mes commandes de produits quand le stock est bas.",
      "Envoie mes factures fournisseurs sur mon outil de compta.",
    ],
  },
  {
    slug: "avocat",
    emoji: "\u{1F468}\u{200D}\u{2696}\u{FE0F}",
    badge: "Avocat",
    title: "Avocat",
    demandes: [
      "Fais un point sur mes mails chaque matin et priorise les échéances de procédure.",
      "Résume les pièces reçues d'un client pour un dossier en cours.",
      "Relance les clients dont les honoraires sont en attente de paiement.",
      "Prépare un premier brouillon de courrier à partir de mes modèles.",
      "Gère la prise de rendez-vous en évitant les conflits avec mes audiences.",
      "Surveille les délais de procédure et alerte-moi avant chaque échéance.",
    ],
  },
  {
    slug: "expert-comptable",
    emoji: "\u{1F4CA}",
    badge: "Expert-comptable",
    title: "Expert-comptable",
    demandes: [
      "Relance les clients qui n'ont pas envoyé leurs justificatifs du mois.",
      "Fais un premier tri des factures reçues, client par client, avant l'intégration en compta.",
      "Fais un point sur mes mails chaque matin et priorise les demandes urgentes.",
      "Prépare les rappels d'échéances fiscales et sociales pour chaque client.",
      "Gère les rendez-vous clients selon les périodes de bilan.",
      "Réponds aux questions simples et récurrentes par mail, transfère-moi les autres.",
    ],
  },
  {
    slug: "kine",
    emoji: "\u{1F9D1}\u{200D}\u{2695}\u{FE0F}",
    badge: "Kiné / Ostéo",
    title: "Kinésithérapeute / Ostéopathe",
    demandes: [
      "Gère les rendez-vous et les annulations de dernière minute : propose le créneau à la liste d'attente.",
      "Relance les patients en rééducation qui n'ont pas repris rendez-vous.",
      "Prépare mes comptes-rendus de séance à partir de mes notes vocales.",
      "Réponds au téléphone en dehors de mes horaires de consultation.",
      "Fais un point sur mes mails et dis-moi s'il y a quelque chose d'important.",
      "Envoie mes notes d'honoraires sur mon outil de compta.",
    ],
  },
  {
    slug: "architecte-interieur",
    emoji: "\u{1F3A8}",
    badge: "Architecte d'intérieur",
    title: "Architecte d'intérieur",
    demandes: [
      "Prépare un premier moodboard à partir des envies décrites par le client.",
      "Relance les clients qui n'ont pas validé un devis ou un plan.",
      "Gère mon planning entre rendez-vous chantier et rendez-vous client.",
      "Fais un point chaque matin sur mes mails fournisseurs et artisans.",
      "Prépare mes factures d'honoraires et envoie-les sur Qonto.",
      "Suis l'avancement de mes chantiers et signale-moi les retards.",
    ],
  },
  {
    slug: "consultant",
    emoji: "\u{1F4BC}",
    badge: "Consultant",
    title: "Consultant / Coach indépendant",
    demandes: [
      "Fais un point sur mes mails chaque matin, même s'il n'y a rien d'important.",
      "Relance les prospects qui n'ont pas donné suite après un premier échange.",
      "Prépare mes factures de mission et envoie-les sur Qonto ou Revolut Business.",
      "Gère les rendez-vous de mes clients selon mes disponibilités réelles.",
      "Prépare un compte-rendu de séance ou de mission à partir de mes notes.",
      "Rédige un premier brouillon de proposition commerciale à partir d'un brief.",
    ],
  },
  {
    slug: "photographe",
    emoji: "\u{1F4F7}",
    badge: "Photographe",
    title: "Photographe",
    demandes: [
      "Réponds aux demandes de devis reçues par mail ou Instagram et propose mes formules.",
      "Relance les clients qui n'ont pas validé leur devis.",
      "Gère mon planning de shootings en gardant du temps pour la retouche et la livraison.",
      "Prépare mes factures et envoie-les sur mon outil de compta.",
      "Fais un point sur mes mails et dis-moi s'il y a quelque chose d'important.",
      "Réponds aux messages Instagram sur mes disponibilités et mes tarifs.",
    ],
  },
  {
    slug: "garagiste",
    emoji: "\u{1F697}",
    badge: "Garagiste",
    title: "Garagiste / Mécanicien auto",
    demandes: [
      "Réponds au téléphone et prends les rendez-vous, même en dehors des horaires d'atelier.",
      "Prépare un devis à partir de la panne décrite par le client.",
      "Organise le planning de l'atelier selon le temps estimé par réparation.",
      "Commande les pièces manquantes chez mes fournisseurs quand le stock est bas.",
      "Relance les clients pour les entretiens à prévoir selon le kilométrage.",
      "Envoie mes factures sur mon outil de compta.",
    ],
  },
  // Deux profils hors metier, en fin de liste : ils elargissent la cible
  // au-dela des pros sans se melanger aux metiers.
  {
    slug: "chercheur-emploi",
    emoji: "\u{1F3AF}",
    badge: "Chercheur d'emploi",
    title: "Chercheur d'emploi",
    demandes: [
      "Surveille les offres qui correspondent à mon profil et envoie-les-moi chaque matin.",
      "Adapte mon CV et ma lettre de motivation à cette offre.",
      "Relance les recruteurs sans réponse depuis plus d'une semaine.",
      "Tiens à jour le tableau de mes candidatures : envoyées, relancées, entretiens.",
      "Prépare-moi à cet entretien : questions probables et infos clés sur l'entreprise.",
      "Fais un point sur mes mails et dis-moi si un recruteur a répondu.",
    ],
  },
  {
    slug: "vie-personnelle",
    emoji: "\u{1F9D8}",
    badge: "Vie personnelle",
    title: "Vie personnelle",
    demandes: [
      "Fais le tri dans mes mails perso et désabonne-moi des newsletters que je n'ouvre jamais.",
      "Prends-moi un rendez-vous chez le médecin et ajoute-le à mon agenda.",
      "Surveille mes abonnements et préviens-moi avant chaque renouvellement.",
      "Compare les offres pour mon assurance et mon forfait, dis-moi si je peux payer moins cher.",
      "Prépare l'itinéraire et le budget de mon prochain week-end, avec 3 options.",
      "Rappelle-moi les anniversaires à venir et prépare un petit message pour chacun.",
    ],
  },
];

export function getMetier(slug) {
  return METIERS.find((m) => m.slug === slug);
}
